name: modal_progress_hud_nsn
description: A modal progress indicator widget with Sound Null Safety. A fork of https://github.com/mmcc007/modal_progress_hud
version: 0.4.0
#author: Phani Pavan K
homepage: https://github.com/kphanipavan/modal_progress_hud_nsn

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: boi.walle.modal_progress_hud_nsn
        pluginClass: ModalProgressHudNsnPlugin
      ios:
        pluginClass: ModalProgressHudNsnPlugin
      linux:
        pluginClass: ModalProgressHudNsnPlugin
      macos:
        pluginClass: ModalProgressHudNsnPlugin
      windows:
        pluginClass: ModalProgressHudNsnPluginCApi
      web:
        pluginClass: ModalProgressHudNsnWeb
        fileName: modal_progress_hud_nsn_web.dart
