name: modal_progress_hud_nsn
description: A modal progress indicator widget with Sound Null Safety. A fork of https://github.com/mmcc007/modal_progress_hud
version: 0.1.0-nullsafety-0
author: Phani Pavan K
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.walle.modal_progress_hud_nsn
        pluginClass: ModalProgressHudNsnPlugin
      ios:
        pluginClass: ModalProgressHudNsnPlugin